spring.data.mongodb.uri = mongodb+srv://rnidaanjum71:EYQAO17IoGuioaN0@cluster0.aeg89es.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database= journaldb
spring.data.mongodb.auto-index-creation= true
spring.application.name = demo
logging.level.com.example.demo = DEBUG
